spring.application.name=Task
spring.datasource.url=jdbc:postgresql://192.168.0.105:5432/postgre
spring.datasource.username=postgre
spring.datasource.password=postgre

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
