server.port=8080
spring.application.name=Task

# =========================
# Database
# =========================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Flyway
# =========================

spring.flyway.enabled=true

# =========================
# Redis
# =========================

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:}

# =========================
# Session
# =========================

spring.session.store-type=redis
server.servlet.session.timeout=${SESSION_TIMEOUT:30m}

# =========================
# Cookie Security
# =========================

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:false}
server.servlet.session.cookie.same-site=lax
